# imports
# standard imports
import numpy as np
import pandas as pd
# visualization
import seaborn as sns
import matplotlib.pyplot as plt
# models
import visuals
#warnings
import warnings
warnings.filterwarnings('ignore')

def initial_visuals(df):
    plt.figure(figsize=[15,15])
    plt.subplot(421)
    sns.boxplot(df.fixed_acidity, df.index)
    plt.subplot(422)
    sns.barplot(df.fixed_acidity, df.index)
    plt.subplot(423)
    sns.boxplot(df.volatile_acidity, df.index)
    plt.subplot(424)
    sns.barplot(df.volatile_acidity, df.index)
    plt.subplot(425)
    sns.boxplot(df.citric_acid, df.index)
    plt.subplot(426)
    sns.barplot(df.citric_acid, df.index)
    plt.subplot(427)
    sns.boxplot(df.residual_sugar, df.index)
    plt.subplot(428)
    sns.barplot(df.residual_sugar, df.index)
    plt.tight_layout()
    plt.show()
    plt.figure(figsize=[15,15])
    plt.subplot(421)
    sns.boxplot(df.chlorides, df.index)
    plt.subplot(422)
    sns.barplot(df.chlorides, df.index)
    plt.subplot(423)
    sns.boxplot(df.free_sulfur_dioxide, df.index)
    plt.subplot(424)
    sns.barplot(df.free_sulfur_dioxide, df.index)
    plt.subplot(425)
    sns.boxplot(df.total_sulfur_dioxide, df.index)
    plt.subplot(426)
    sns.barplot(df.total_sulfur_dioxide, df.index)
    plt.subplot(427)
    sns.boxplot(df.density, df.index)
    plt.subplot(428)
    sns.barplot(df.density, df.index)
    plt.tight_layout()
    plt.show()
    plt.figure(figsize=[15,15])
    plt.subplot(421)
    sns.boxplot(df.pH, df.index)
    plt.subplot(422)
    sns.barplot(df.pH, df.index)
    plt.subplot(423)
    sns.boxplot(df.sulphates, df.index)
    plt.subplot(424)
    sns.barplot(df.sulphates, df.index)
    plt.subplot(425)
    sns.boxplot(df.alcohol, df.index)
    plt.subplot(426)
    sns.barplot(df.alcohol, df.index)
    plt.subplot(427)
    sns.boxplot(df.quality, df.index)
    plt.subplot(428)
    sns.barplot(df.quality, df.index)
    plt.tight_layout()
    plt.show()
    plt.figure(figsize=[15,15])
    plt.subplot(421)
    sns.scatterplot(df.fixed_acidity, df.index)
    plt.subplot(422)
    sns.scatterplot(df.volatile_acidity, df.index)
    plt.subplot(423)
    sns.scatterplot(df.citric_acid, df.index)
    plt.subplot(424)
    sns.scatterplot(df.residual_sugar, df.index)
    plt.subplot(425)
    sns.scatterplot(df.chlorides, df.index)
    plt.subplot(426)
    sns.scatterplot(df.free_sulfur_dioxide, df.index)
    plt.subplot(427)
    sns.scatterplot(df.total_sulfur_dioxide, df.index)
    plt.subplot(428)
    sns.scatterplot(df.density, df.index)
    plt.tight_layout()
    plt.show()
    plt.figure(figsize=[15,15])
    plt.subplot(421)
    sns.scatterplot(df.pH, df.index)
    plt.subplot(422)
    sns.scatterplot(df.sulphates, df.index)
    plt.subplot(423)
    sns.scatterplot(df.alcohol, df.index)
    plt.subplot(424)
    sns.scatterplot(df.quality, df.index)
    plt.tight_layout()
    plt.show()

